terraform {
  # PARTIAL backend configuration, matching dev and prod.
  #
  # The bucket name is deliberately absent because S3 bucket names are globally
  # unique and therefore embed the AWS account ID, which should not be a literal
  # in a public repository. The rest comes from backend.hcl, which is gitignored
  # and generated by `make bootstrap`:
  #
  #   cd terraform/bootstrap
  #   terraform output -raw backend_hcl > ../environments/ci/backend.hcl
  #
  # `make init ENV=ci` does the init for you.
  backend "s3" {
    key = "env/ci/terraform.tfstate"

    # Native S3 state locking. See terraform/environments/dev/backend.tf and
    # docs/architecture.md section 4 for why there is no DynamoDB table.
    use_lockfile = true

    encrypt = true
  }
}
