terraform {
  # PARTIAL backend configuration.
  #
  # The bucket name is deliberately absent. S3 bucket names are globally unique
  # across all of AWS, so it has to include an account ID, which means it cannot
  # be committed as a literal in a public repository. The remaining values come
  # from backend.hcl, which is gitignored and generated by `make bootstrap`:
  #
  #   terraform init -backend-config=backend.hcl
  #
  # The Makefile does this for you.
  backend "s3" {
    key = "env/dev/terraform.tfstate"

    # Native S3 state locking, added in Terraform 1.10 and the replacement for the
    # deprecated dynamodb_table argument. Terraform writes a zero byte
    # <key>.tflock object using an S3 conditional write (If-None-Match), which is
    # atomic. If the object already exists the lock is held and the apply is
    # refused.
    #
    # This removes a whole DynamoDB table, its IAM permissions and its cost, and
    # removes the failure mode where the lock table and the state bucket drift
    # apart.
    use_lockfile = true

    encrypt = true
  }
}
